name: Terraform Format and Validate

on:
  pull_request:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      - name: Check Terraform version
        run: terraform --version
      
      - name: Initialize terraform
        run: terraform init
        
      - name: List files in repo
        run: ls -R  # Debug step to list files

      - name: Run terraform fmt
        run: terraform fmt -check -recursive

      - name: Run terraform validate
        run: terraform validate
